In [1]:
import numpy as np

In [2]:
variables = [
    "Climate",
    "Housing",
    "Health",
    "Crime",
    "Transportation",
    "Education",
    "Arts",
    "Recreation",
    "Economy"
]

In [3]:
loadings = np.array([
    [0.190,  0.017,  0.207],
    [0.544,  0.020,  0.204],
    [0.782, -0.605,  0.144],
    [0.365,  0.294,  0.585],
    [0.585,  0.085,  0.234],
    [0.394, -0.273,  0.027],
    [0.985,  0.126, -0.111],
    [0.520,  0.402,  0.519],
    [0.142,  0.150,  0.239]
])

In [4]:
absolute_loadings = np.abs(loadings)

print(absolute_loadings)

[[0.19  0.017 0.207]
 [0.544 0.02  0.204]
 [0.782 0.605 0.144]
 [0.365 0.294 0.585]
 [0.585 0.085 0.234]
 [0.394 0.273 0.027]
 [0.985 0.126 0.111]
 [0.52  0.402 0.519]
 [0.142 0.15  0.239]]


In [5]:
max_indices = np.argmax(absolute_loadings, axis=0)

print(max_indices)

[6 2 3]


In [6]:
for i in range(3):
    index = max_indices[i]
    print(
        "PC", i + 1,
        "=", variables[index],
        "Loading =", loadings[index, i]
    )

PC 1 = Arts Loading = 0.985
PC 2 = Health Loading = -0.605
PC 3 = Crime Loading = 0.585
